# Generated by Django 4.0.4 on 2022-05-16 07:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^[a-zA-z][a-zA-Z]+[a-zA-Z]*$', 'Only Alphabets allowed')])),
                ('mobile', models.BigIntegerField(default=0, validators=[django.core.validators.RegexValidator('^[5-9][0-9]{9}$', 'Enter 10 digits mobile number')])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
