# Generated by Django 4.0.4 on 2022-05-16 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only Numbers allowed')]),
        ),
    ]
