# Generated by Django 4.0.4 on 2022-05-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0004_doctor_medicalregno'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='academicinfo',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
