# Generated by Django 4.0.4 on 2022-05-29 11:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0005_doctor_academicinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(default=datetime.datetime.now)),
                ('appointment_time', models.TimeField()),
                ('appoint_status', models.CharField(default='Pending', max_length=60)),
                ('patient_message', models.CharField(max_length=260)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cancer.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cancer.patient')),
            ],
        ),
    ]
