from datetime import datetime
from statistics import mode
from django.db import models
from django.contrib.auth.models import User
gender_choices=((0 , 'Female'), (1 ,'Male'))

# Create your models here.
class Predictions(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    predicted_on = models.DateTimeField(default=datetime.now)
    age = models.IntegerField()
    gender = models.IntegerField(choices=gender_choices, default=0)
    air_polution = models.IntegerField(default=0)
    alcohol = models.IntegerField(default=0)
    dust_alergy = models.IntegerField(default=0)
    chronic_lung_disease = models.IntegerField(default=0)
    balanced_diet = models.IntegerField(default=0)
    obesity = models.IntegerField(default=0)
    smoking = models.IntegerField(default=0)
    passive_smoking = models.IntegerField(default=0)
    chest_pain = models.IntegerField(default=0)
    coughing_of_blood = models.IntegerField(default=0)
    fatigue = models.IntegerField(default=0)
    weight_loss = models.IntegerField(default=0)
    shortness_of_breath = models.IntegerField(default=0)
    weezing = models.IntegerField(default=0)
    swallowing_dificulty = models.IntegerField(default=0)
    clubbing_of_nails = models.IntegerField(default=0)
    frequent_cold = models.IntegerField(default=0)
    dry_cough = models.IntegerField(default=0)
    hoarseness = models.IntegerField(default=0)
    headache = models.IntegerField(default=0)
    loss_of_memmory = models.IntegerField(default=0)
    red_spot_in_skin = models.IntegerField(default=0)
    fever = models.IntegerField(default=0)
    nose_bleeding = models.IntegerField(default=0)
    bleeding_easily = models.IntegerField(default=0)
    night_sweating = models.IntegerField(default=0)
    vomiting = models.IntegerField(default=0)
    abdomen_discomfort = models.IntegerField(default=0)
    bleeding_stools = models.IntegerField(default=0)
    jaundice = models.IntegerField(default=0)
    stomach_pain = models.IntegerField(default=0)
    num=models.IntegerField()